<?php
include 'index.php';
include 'db_connect.php';
$connect = odbc_connect("SIT", "palagi01", "s1mple01");
# query the users table for name and surname
$sqlop = new db_connect();
$result = $sqlop->db('SELECT  * FROM DI_test_records_V where rownum<2');
# perform the query
#$result = odbc_exec($connect, $query);

$xml = new DOMDocument("1.0","utf-8");
$xml->formatOutput =true;
#$root = $xml->createElementNS('http://www.cancerresearchuk.org/di/r17/supplier/newdonate');
$gen=$xml->createElementNS("http://www.cancerresearchuk.org/di/r17/supplier/generic","batch");
$xml->appendChild($gen);
$id=$xml->createElement("id",date('YmdHis'));
$gen->appendChild($id);
$ltran=$xml->createElement("listOfTransaction");
$gen->appendChild($ltran);
$tran=$xml->createElement("transaction");
$ltran->appendChild($tran);
while($row=odbc_fetch_row($result)){
	$Trefe=$xml->createElement("reference",odbc_result($result, 1));
	$tran->appendChild($Trefe);
	$supporter=$xml->createElement("supporter");
	$tran->appendChild($supporter);
	$dob = $xml->createElement("dateOfBirth",odbc_result($result, 2));
	$supporter->appendChild($dob);
	$pExtRef = $xml->createElement("primaryExternalReferenceId",odbc_result($result, 3));
	$supporter->appendChild($pExtRef);
	$secondaryExternalReferenceId = $xml->createElement("secondaryExternalReferenceId",odbc_result($result, 4));
	$supporter->appendChild($secondaryExternalReferenceId);
	$PDataSo = $xml->createElement("primaryDataSourceCode",odbc_result($result, 5));
	$supporter->appendChild($PDataSo);
	$secondaryDataSourceCode = $xml->createElement("secondaryDataSourceCode",odbc_result($result, 6));
	$supporter->appendChild($secondaryDataSourceCode);	
	$fore=$xml->createElement("forename",odbc_result($result, 7));
	$supporter->appendChild($fore);
	$gender=$xml->createElement("gender",odbc_result($result, 8));
	$supporter->appendChild($gender);
	$initial=$xml->createElement("initial",odbc_result($result, 9));
	$supporter->appendChild($initial);
	$SSdate = $xml->createElement("startDate",odbc_result($result, 10));
	$supporter->appendChild($SSdate);
	$SSource=$xml->createElement("source",odbc_result($result, 11));
	$supporter->appendChild($SSource);
	$SStatus=$xml->createElement("statusCode",odbc_result($result, 12));
	$supporter->appendChild($SStatus);
	$SStDate=$xml->createElement("statusDate",odbc_result($result, 13));
	$supporter->appendChild($SStDate);
	$suffix=$xml->createElement("suffix",odbc_result($result, 14));
	$supporter->appendChild($suffix);
	$SuppURN=$xml->createElement("supporterURN",odbc_result($result, 15));
	$supporter->appendChild($SuppURN);
	$surname=$xml->createElement("surname",odbc_result($result, 16));
	$supporter->appendChild($surname);
	$Title=$xml->createElement("title",odbc_result($result, 17));
	$supporter->appendChild($Title);
	$changeofNameIndicator=$xml->createElement("changeofNameIndicator",odbc_result($result, 18));
	$supporter->appendChild($changeofNameIndicator);
	$nonTaxPayerFlag=$xml->createElement("nonTaxPayerFlag",odbc_result($result, 19));
	$supporter->appendChild($nonTaxPayerFlag);
	$nonTaxPayerStartDate=$xml->createElement("nonTaxPayerStartDate",odbc_result($result, 20));
	$supporter->appendChild($nonTaxPayerStartDate);
	$dateOfDeath=$xml->createElement("dateOfDeath",odbc_result($result, 21));
	$supporter->appendChild($dateOfDeath);
	$deathNotificationDate=$xml->createElement("deathNotificationDate",odbc_result($result, 22));
	$supporter->appendChild($deathNotificationDate);
	$maritalStatus=$xml->createElement("maritalStatus",odbc_result($result, 23));
	$supporter->appendChild($maritalStatus);
	$address=$xml->createElement("address");
	$supporter->appendChild($address);
	$addressLine1=$xml->createElement("addressLine1",odbc_result($result, 24));
	$address->appendChild($addressLine1);
	$addressLine2=$xml->createElement("addressLine2",odbc_result($result, 25));
	$address->appendChild($addressLine2);
	$addressLine3=$xml->createElement("addressLine3",odbc_result($result, 26));
	$address->appendChild($addressLine3);
	$addressLine4=$xml->createElement("addressLine4",odbc_result($result, 27));
	$address->appendChild($addressLine4);
	$cherishedAddressHouseName=$xml->createElement("cherishedAddressHouseName",odbc_result($result, 28));
	$address->appendChild($cherishedAddressHouseName);
	$city=$xml->createElement("city",odbc_result($result, 29));
	$address->appendChild($city);
	$country=$xml->createElement("country",odbc_result($result, 30));
	$address->appendChild($country);
	$county=$xml->createElement("county",odbc_result($result, 31));
	$address->appendChild($county);
	$postalCode=$xml->createElement("postalCode",odbc_result($result, 32));
	$address->appendChild($postalCode);
	$startDate=$xml->createElement("startDate",odbc_result($result, 33));
	$address->appendChild($startDate);
	$validationStatus=$xml->createElement("validationStatus",odbc_result($result, 34));
	$address->appendChild($validationStatus);
	$newAddressIndicator=$xml->createElement("newAddressIndicator",odbc_result($result, 35));
	$address->appendChild($newAddressIndicator);
	$secondaryAddresses=$xml->createElement("secondaryAddresses");
	$supporter->appendChild($secondaryAddresses);
	$saddresses=$xml->createElement("address");
	$secondaryAddresses->appendChild($saddresses);
	$saddressLine1=$xml->createElement("addressLine1",odbc_result($result, 36));
	$saddresses->appendChild($saddressLine1);
	$saddressLine2=$xml->createElement("addressLine2",odbc_result($result, 37));
	$saddresses->appendChild($saddressLine2);
	$saddressLine3=$xml->createElement("addressLine3",odbc_result($result, 38));
	$saddresses->appendChild($saddressLine3);
	$saddressLine4=$xml->createElement("addressLine4",odbc_result($result, 39));
	$saddresses->appendChild($saddressLine4);
	$scherishedAddressHouseName=$xml->createElement("cherishedAddressHouseName",odbc_result($result, 40));
	$saddresses->appendChild($scherishedAddressHouseName);
	$scity=$xml->createElement("city",odbc_result($result, 41));
	$saddresses->appendChild($scity);
	$scountry=$xml->createElement("country",odbc_result($result, 42));
	$saddresses->appendChild($scountry);
	$scounty=$xml->createElement("county",odbc_result($result, 43));
	$saddresses->appendChild($scounty);	
	$spostalCode=$xml->createElement("postalCode",odbc_result($result, 44));
	$saddresses->appendChild($spostalCode);
	$astartDate=$xml->createElement("startDate",odbc_result($result, 45));
	$saddresses->appendChild($astartDate);
	$svalidationStatus=$xml->createElement("validationStatus",odbc_result($result, 46));
	$saddresses->appendChild($svalidationStatus);
	$snewAddressIndicator=$xml->createElement("newAddressIndicator",odbc_result($result, 47));
	$saddresses->appendChild($snewAddressIndicator);
	
}
#echo odbc_num_rows(odbc_exec($connect, $cou));
#echo "<xml>".$xml->saveXML()."</xml>";
$xml->formatOutput =true;
$xml->save("report.xml");
?>